In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [16]:
path='/content/drive/MyDrive/KT-BigProject/'

In [26]:
data_df=pd.read_csv(path+'Home_data_final.csv')

In [ ]:
data_df.head()

Name          Address   Latitude   Longitude Supply_type  \
0  S-HOUSE    성동구 고산자로17길 9  37.567360  127.035712         21B   
1  S-HOUSE  성동구 고산자로17길 9-1  37.567382  127.035586         21B   
2    STAY온  관악구 남부순환로157길 3  37.484155  126.918585         17B   
3    STAY온  관악구 남부순환로157길 3  37.484155  126.918585         26B   
4    STAY온   관악구 남부순환로 1519  37.479901  126.940463         17B   

   Applicant_type  Units  Gender  Shared  Cutline_rate  ...  Counts_laundry  \
0               0     12       2       0             1  ...               5   
1               0     12       2       0             1  ...               5   
2               0     23       2       0             2  ...              15   
3               0     24       2       0             2  ...              15   
4               0     16       2       0             2  ...              12   

   Counts_pharmacy  Counts_cafe  Counts_convstore  Counts_station  \
0                7           15                15               7   
1                7           15                15               7   
2               15           15                15               3   
3               15           15                15               3   
4               15           15                15               2   

   Infra_score  people  Rate1  Rate2  Rate3  
0         4.30     458     34    154    270  
1         4.30     442     32    148    262  
2         4.85     296     19    100    177  
3         4.85     435     24    146    265  
4         4.83     175     11     59    105  

[5 rows x 26 columns]

In [ ]:
data_df.describe()

Latitude   Longitude  Applicant_type       Units      Gender  \
count  876.000000  876.000000      876.000000  876.000000  876.000000   
mean    37.535154  126.992455        0.063927    7.278539    1.880137   
std      0.049119    0.099948        0.244762   18.401864    0.422799   
min     37.452199  126.829792        0.000000    1.000000    0.000000   
25%     37.495240  126.904131        0.000000    1.000000    2.000000   
50%     37.531212  127.007393        0.000000    3.000000    2.000000   
75%     37.562015  127.082701        0.000000    7.000000    2.000000   
max     37.669586  127.172139        1.000000  349.000000    2.000000   

           Shared  Cutline_rate  Cutline_score         Year     Quarter  ...  \
count  876.000000    876.000000     876.000000   876.000000  876.000000  ...   
mean     0.086758      1.384703       5.734018  2022.847032    1.621005  ...   
std      0.281641      0.560974       2.354091     0.940214    0.593463  ...   
min      0.000000      1.000000       0.000000  2021.000000    1.000000  ...   
25%      0.000000      1.000000       4.000000  2022.000000    1.000000  ...   
50%      0.000000      1.000000       6.000000  2023.000000    2.000000  ...   
75%      0.000000      2.000000       7.000000  2024.000000    2.000000  ...   
max      1.000000      3.000000      11.000000  2024.000000    3.000000  ...   

       Counts_laundry  Counts_pharmacy  Counts_cafe  Counts_convstore  \
count      876.000000       876.000000   876.000000        876.000000   
mean         5.111872        11.144977    14.866438         14.257991   
std          3.298318         4.505310     0.931587          2.144946   
min          0.000000         0.000000     6.000000          4.000000   
25%          3.000000         8.000000    15.000000         15.000000   
50%          5.000000        13.000000    15.000000         15.000000   
75%          7.000000        15.000000    15.000000         15.000000   
max         15.000000        15.000000    15.000000         15.000000   

       Counts_station  Infra_score        people       Rate1        Rate2  \
count      876.000000   876.000000    876.000000  876.000000   876.000000   
mean         3.484018     4.310331    421.234018   22.123288   179.265982   
std          2.318812     0.574620    949.469679   42.170791   456.635383   
min          0.000000     1.320000      2.000000    0.000000     0.000000   
25%          2.000000     4.220000     57.000000    3.000000    19.000000   
50%          3.000000     4.470000    149.000000    9.000000    52.000000   
75%          5.000000     4.650000    411.000000   24.000000   152.500000   
max         13.000000     4.930000  15600.000000  546.000000  7696.000000   

             Rate3  
count   876.000000  
mean    219.878995  
std     462.775252  
min       0.000000  
25%      32.000000  
50%      86.000000  
75%     224.500000  
max    7358.000000  

[8 rows x 23 columns]

In [ ]:
data_df.columns

Index(['Name', 'Address', 'Latitude', 'Longitude', 'Supply_type',
       'Applicant_type', 'Units', 'Gender', 'Shared', 'Cutline_rate',
       'Cutline_score', 'Year', 'Quarter', 'Applied_type', 'Counts_daiso',
       'Counts_supermarket', 'Counts_laundry', 'Counts_pharmacy',
       'Counts_cafe', 'Counts_convstore', 'Counts_station', 'Infra_score',
       'people', 'Rate1', 'Rate2', 'Rate3'],
      dtype='object')

## 데이터 준비
- 전처리는 끝난 데이터이므로 size에 대해서만 문자열 분리 진행
- 의문? 뒤에 A형 B형은 일단 그냥 버려야 하나
- Name, Address는 drop 해야함

In [8]:
!pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 8.3 MB/s eta 0:00:00


In [9]:
# 라이브러리
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler
from lightgbm import LGBMRegressor
from sklearn.metrics import *
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Input,Dense,Dropout,BatchNormalization
from keras.callbacks import EarlyStopping
from sklearn.multioutput import ClassifierChain
from catboost import CatBoostClassifier, CatBoostRegressor, Pool

In [27]:
# size에 대한 전처리
data_df['Supply_type'] = data_df['Supply_type'].str.extract('(\d+\.?\d*)').astype(float)

# Name Address 처리
data_df=data_df.drop(columns=['Name','Address'])

## 기본 데이터처리 ( 1번에서만 사용했음 )




1) x,y 분리

In [ ]:
# target이 뭐야 : 순위랑 점수
target=['Cutline_rate','Cutline_score']

# x,y 분리
x=data_df.drop(columns=target)
y=data_df[target]

In [ ]:
x.columns

Index(['Latitude', 'Longitude', 'Supply_type', 'Applicant_type', 'Units',
       'Gender', 'Shared', 'Year', 'Quarter', 'Applied_type', 'Counts_daiso',
       'Counts_supermarket', 'Counts_laundry', 'Counts_pharmacy',
       'Counts_cafe', 'Counts_convstore', 'Counts_station', 'Infra_score',
       'people', 'Rate1', 'Rate2', 'Rate3'],
      dtype='object')

In [ ]:
y.columns

Index(['Cutline_rate', 'Cutline_score'], dtype='object')

In [ ]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876 entries, 0 to 875
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Cutline_rate   876 non-null    int64
 1   Cutline_score  876 non-null    int64
dtypes: int64(2)
memory usage: 13.8 KB


2) 학습용 평가용 분리

옵션 : test_size=0.3 , random_state=25 , stratify=y > 이거 오류나서 안됨 쓰지마

In [ ]:
# 데이터분리
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)

3) 스케일링은 일단 안할게요

## 모델링1 MultiOutPutRegressor 활용해보기
- 성능이 나쁘진 않은데,, 그냥 그정도임 r2 score가 처참

In [ ]:
!pip install lightgbm

In [ ]:
from lightgbm import LGBMRegressor
from sklearn.multioutput import MultiOutputRegressor

In [ ]:
# 선언하기
# verbose = -1 : 학습과정을 안보이게 해주는 설정
# importance_type = 'split' : 분할에 사용된 횟수 : 디폴트 값임
# importance_type = 'gain' : 이 변수가 100개의 트리에서 줄인 손실의 수

model = MultiOutputRegressor(LGBMRegressor(max_depth=5, verbose=-1, importance_type='split'))

In [ ]:
# 학습하기
model.fit(x_train,y_train)

MultiOutputRegressor(estimator=LGBMRegressor(max_depth=5, verbose=-1))

) y_pred 값에 대한 처리 필요함 > 반올림을 하던가 필요할듯

In [ ]:
y_pred=model.predict(x_test)

# 가볍게 반올림
y_pred=y_pred.round().astype(int)

In [ ]:
mae_all = mean_absolute_error(y_test, y_pred, multioutput='raw_values')
# array([mae_for_target1, mae_for_target2])

r2_all = r2_score(y_test, y_pred, multioutput='raw_values')
# array([r2_for_target1, r2_for_target2])

print("MAE for rate:", mae_all[0])
print("MAE for score:", mae_all[1])
print("R2  for rate,score:", r2_all)

MAE for rate: 0.19011406844106463
MAE for score: 1.6197718631178708
R2  for rate,score: [0.25596922 0.03127533]


In [ ]:
y_pred

array([[ 2,  5],
       [ 1,  7],
       [ 1,  5],
       [ 2,  5],
       [ 1,  4],
       [ 1,  5],
       [ 1,  6],
       [ 1,  7],
       [ 1,  5],
       [ 2,  5],
       [ 1,  9],
       [ 1,  6],
       [ 1,  7],
       [ 1,  6],
       [ 1,  5],
       [ 2,  4],
       [ 1,  5],
       [ 2,  1],
       [ 1,  4],
       [ 1,  6],
       [ 1,  6],
       [ 1,  6],
       [ 1,  8],
       [ 1,  6],
       [ 2,  6],
       [ 1,  4],
       [ 1,  6],
       [ 1,  4],
       [ 1,  5],
       [ 1,  4],
       [ 1,  6],
       [ 2,  6],
       [ 1, 10],
       [ 2,  7],
       [ 2,  4],
       [ 2,  7],
       [ 1, 10],
       [ 1,  7],
       [ 2,  5],
       [ 1,  8],
       [ 2,  5],
       [ 1,  3],
       [ 1,  7],
       [ 1,  7],
       [ 2,  3],
       [ 1,  6],
       [ 1,  7],
       [ 1,  4],
       [ 1,  8],
       [ 1,  6],
       [ 1,  7],
       [ 1,  8],
       [ 1,  8],
       [ 1,  5],
       [ 2,  6],
       [ 1,  3],
       [ 1,  7],
       [ 1,  7],
       [ 2,  5

In [ ]:
y_test.values

array([[ 2,  5],
       [ 1,  0],
       [ 1,  4],
       [ 2,  8],
       [ 1,  7],
       [ 1,  3],
       [ 2,  8],
       [ 2,  2],
       [ 1,  6],
       [ 2,  7],
       [ 1,  6],
       [ 1,  8],
       [ 1,  3],
       [ 1,  5],
       [ 2,  9],
       [ 2,  6],
       [ 1,  4],
       [ 3,  4],
       [ 1,  2],
       [ 1,  2],
       [ 1,  7],
       [ 2,  7],
       [ 1,  8],
       [ 1,  5],
       [ 2,  8],
       [ 2,  5],
       [ 1,  6],
       [ 1,  4],
       [ 1,  7],
       [ 2,  2],
       [ 1,  6],
       [ 2,  8],
       [ 1,  8],
       [ 1,  0],
       [ 2,  5],
       [ 2,  7],
       [ 1,  9],
       [ 1,  5],
       [ 2,  7],
       [ 1,  9],
       [ 2,  5],
       [ 1,  4],
       [ 1,  8],
       [ 1,  7],
       [ 3,  2],
       [ 1,  7],
       [ 2,  7],
       [ 1,  5],
       [ 1,  9],
       [ 2,  8],
       [ 1,  5],
       [ 1,  8],
       [ 1,  7],
       [ 1,  3],
       [ 1,  5],
       [ 1,  5],
       [ 1,  5],
       [ 1,  5],
       [ 2,  8

## 모델링 2 , 하나하나씩 따로 해보기  > SCORE 성능이 너무 안좋음

### rate

1 ) 일단 x, y 정의부터 다시해야함

In [ ]:
# target
target='Cutline_rate'

# x, y
x=data_df.drop(columns=target)
y=data_df[target]

# 추가로 drop 하기
cols=['Latitude','Longitude','people','Infra_score']
x=x.drop(columns=cols)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=25)

In [ ]:
model=LGBMRegressor(max_depth=5, verbose=-1, importance_type='split')

In [ ]:
# 학습하기
model.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The LGBMRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


LGBMRegressor(max_depth=5, verbose=-1)

In [ ]:
y_pred=model.predict(x_test)

# 가볍게 반올림
y_pred=y_pred.round().astype(int)

In [ ]:
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

0.14068441064638784
0.4196559918524385


### score

In [ ]:
# target
target='Cutline_score'

# x, y
x2=data_df.drop(columns=target)
y2=data_df[target]

# 추가로 drop 하기
cols=['Latitude','Longitude','people']
x2=x2.drop(columns=cols)

x_train,x_test,y_train,y_test=train_test_split(x2,y2,test_size=0.3,random_state=25)

In [ ]:
model=LGBMRegressor(max_depth=5, verbose=-1, importance_type='split')
# 학습하기
model.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The LGBMRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


LGBMRegressor(max_depth=5, verbose=-1)

In [ ]:
y_pred=model.predict(x_test)

# 가볍게 반올림
y_pred=y_pred.round().astype(int)

In [ ]:
print(mean_absolute_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

1.4372623574144487
0.18557137500151188


# 모델링3. 통합점수 만들어 예측하기

- 순위 가점을 따로 계산하는 모델은 성능이 너무 떨어짐
- 이에 따라서 새롭게 통합점수를 계산해서 이를 예측하는 회귀 모델을 만들것이다
- 0.25가 일단 한계점인듯한데 0.25가 의미 하는것은

In [76]:
trial_df=data_df.copy()

trial_df.head()

Latitude   Longitude  Supply_type  Applicant_type  Units  Gender  Shared  \
0  37.567360  127.035712         21.0               0     12       2       0   
1  37.567382  127.035586         21.0               0     12       2       0   
2  37.484155  126.918585         17.0               0     23       2       0   
3  37.484155  126.918585         26.0               0     24       2       0   
4  37.479901  126.940463         17.0               0     16       2       0   

   Cutline_rate  Cutline_score  Year  ...  Counts_laundry  Counts_pharmacy  \
0             1              3  2022  ...               5                7   
1             1              2  2022  ...               5                7   
2             2              5  2022  ...              15               15   
3             2              6  2022  ...              15               15   
4             2              5  2022  ...              12               15   

   Counts_cafe  Counts_convstore  Counts_station  Infra_score  people  Rate1  \
0           15                15               7         4.30     458     34   
1           15                15               7         4.30     442     32   
2           15                15               3         4.85     296     19   
3           15                15               3         4.85     435     24   
4           15                15               2         4.83     175     11   

   Rate2  Rate3  
0    154    270  
1    148    262  
2    100    177  
3    146    265  
4     59    105  

[5 rows x 24 columns]

In [88]:
# 통합점수 생성
# 순위와 가산점의 상대 중요도를 조정하는 가중치(alpha, beta)
alpha = 100.0  # 순위 점수에 대한 가중치
beta = 1.0   # 가산점에 대한 가중치

# 통합 점수 계산
# (4 - rate)는 "1순위 -> 3, 2순위 -> 2, 3순위 -> 1" 형태로 점수를 매기는 예시
# (score / 10)은 가산점(0~10점)을 0~1 범위로 정규화한 값
trial_df['Merged_score'] = alpha * (4 - trial_df['Cutline_rate']) + beta * (trial_df['Cutline_score'] / 10)

cols=['Latitude','Longitude','people','Infra_score']

trial_df=trial_df.drop(columns=cols)

trial_df.head()

Supply_type  Applicant_type  Units  Gender  Shared  Cutline_rate  \
0         21.0               0     12       2       0             1   
1         21.0               0     12       2       0             1   
2         17.0               0     23       2       0             2   
3         26.0               0     24       2       0             2   
4         17.0               0     16       2       0             2   

   Cutline_score  Year  Quarter  Applied_type  ...  Counts_supermarket  \
0              3  2022        1             1  ...                   4   
1              2  2022        1             1  ...                   4   
2              5  2022        1             1  ...                   0   
3              6  2022        1             1  ...                   0   
4              5  2022        1             1  ...                   1   

   Counts_laundry  Counts_pharmacy  Counts_cafe  Counts_convstore  \
0               5                7           15                15   
1               5                7           15                15   
2              15               15           15                15   
3              15               15           15                15   
4              12               15           15                15   

   Counts_station  Rate1  Rate2  Rate3  Merged_score  
0               7     34    154    270         300.3  
1               7     32    148    262         300.2  
2               3     19    100    177         200.5  
3               3     24    146    265         200.6  
4               2     11     59    105         200.5  

[5 rows x 21 columns]

- 새로운 로직 생각 해본거

통합점수를 만들때, 순위는 10자리수로 만들어서 예측한다

그리고 숫자가 0 ~5 라면 내리고, 6 ~10 이면 올려서 예측값을 조절해준다
- 이로직을 생각한 이유는 순위가 중요한 부분인데 한자리수 점수에서는 소수점 예측이 잘못되거나 하면 순위가 바뀌어버림
- 이 로직을 적용한 결과 : 순위에 대한것은 3개 정도만 제외하면 잘 들어 맞았다.
 > 그치만 데이터가 부족하니 단정짓지는 말자

- score에 대한 예측 정확도를 어떻게 올릴수있을까

In [20]:
# 모델 예측값 반올림 함수
def custom_round_100(values):
    """
    1) 정수부(int_part)를 얻는다. (예: 225.7 -> 225)
    2) 소수부(dec_part)를 얻는다. (225.7 -> 0.7)
    3) '100의 자리'를 구한다. (225 -> 200)
    4) '나머지' remainder = int_part % 100 (예: 225 -> 25, 256 -> 56)
    5) remainder <= 50이면 아래쪽 100단위(200), remainder > 50이면 윗 100단위(300)로 조정
    6) 소수부는 그대로 더한다.
    """
    results = []
    for val in values:
        int_part = int(val)               # 정수부
        dec_part = val - int_part         # 소수부

        # 100단위로 내려놓기 (예: 225 -> 200, 256 -> 200)
        hundred_floor = (int_part // 100) * 100
        remainder = int_part % 100        # 예: 225 -> 25, 256 -> 56

        if remainder <= 50:
            # 0~50 사이는 아래 100단위
            new_int_part = hundred_floor
        else:
            # 51~99 사이는 위 100단위로 올림
            new_int_part = hundred_floor + 100

        new_val = new_int_part + dec_part
        results.append(new_val)

    return np.array(results)


In [63]:
# 통합점수 역산 함수
def invert_merged_score(merged_val, alpha, beta):
    """
    Merged_score로부터 (rate, score) 후보를 찾는 함수.
    - rate ∈ {1, 2, 3}
    - score ∈ [0, 10]
    - 여러 해가 있을 수 있으므로, 우선 첫 번째 valid 해를 리턴.
    - 만약 어떤 rate로도 0~10 내 score가 안 나오면 (np.nan, np.nan) 반환.
    """
    # print(merged_val)
    # print('********************')
    for rate_candidate in [1, 2, 3]:
        # 수식에 따라 score를 역산
        score_candidate = (10 / beta) * (merged_val - alpha * (4 - rate_candidate))
        score_candidate=round(score_candidate)
        #print(score_candidate)
        # 유효 범위 체크
        if 0 <= score_candidate <= 10:
            return rate_candidate, score_candidate
    # print("***** 계산끝 *********")
    # 만약 어떤 rate도 0~10 범위 만족하는 해가 없다면
    return np.nan, np.nan

In [89]:
# 데이터 분리
target='Merged_score'
x=trial_df.drop(columns=target)
x=x.drop(columns=['Cutline_rate','Cutline_score'])
y=trial_df[target]

# 라벨인코딩
# x['Supply_type'] = LabelEncoder().fit_transform(x['Supply_type'])
# 스케일링
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [93]:
# 데이터셋 분할
x_train,x_val,y_train,y_val=train_test_split(x,y,test_size=0.2,random_state=25)

## 기본 lgbm 모델

In [94]:
# 모델링
model=LGBMRegressor(n_estimators=10)

model.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000141 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 676
[LightGBM] [Info] Number of data points in the train set: 700, number of used features: 17
[LightGBM] [Info] Start training from score 261.428857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: 

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The LGBMRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


LGBMRegressor(n_estimators=10)

In [95]:
y_pred=model.predict(x_val)
y_pred=y_pred.round(1)
y_pred_custom=custom_round_100(y_pred)

print('MAE : ',mean_absolute_error(y_val,y_pred_custom))
print('MSE : ',mean_squared_error(y_val,y_pred_custom))
print('r2 score : ',r2_score(y_val,y_pred_custom))

MAE :  17.876704545454547
MSE :  1869.5948295454548
r2 score :  0.32071802781706504


/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [96]:
# 역산 적용하기
# 예측값을 역산하여 rate와 score 복원
predicted_values = pd.Series(y_pred_custom, index=y_val.index).apply(lambda m: invert_merged_score(m, alpha, beta))
predicted_rate_score = pd.DataFrame(predicted_values.tolist(), index=y_val.index, columns=['Predicted_rate', 'Predicted_score'])

# 원래 값과 예측값 병합
comparison_df = pd.concat([
    trial_df.loc[y_val.index, ['Cutline_rate', 'Cutline_score']],  # 원래 값
    predicted_rate_score  # 예측 값
], axis=1)



In [97]:
# 평가 지표 계산 (rate는 분류, score는 회귀)
rate_accuracy = (comparison_df['Cutline_rate'] == comparison_df['Predicted_rate']).mean()
score_mae = mean_absolute_error(comparison_df['Cutline_score'], comparison_df['Predicted_score'])

print(f"Rate Accuracy: {rate_accuracy * 100:.2f}%")
print(f"Score MAE: {score_mae:.4f}")


print(confusion_matrix(comparison_df['Cutline_rate'], comparison_df['Predicted_rate']))

# Classification Report 출력
print("Classification Report for Rate Prediction:")
print(classification_report(comparison_df['Cutline_rate'], comparison_df['Predicted_rate'], digits=2))

Rate Accuracy: 82.95%
Score MAE: 3.4148
[[107  10   0]
 [ 16  39   0]
 [  1   3   0]]
Classification Report for Rate Prediction:
              precision    recall  f1-score   support

           1       0.86      0.91      0.89       117
           2       0.75      0.71      0.73        55
           3       0.00      0.00      0.00         4

    accuracy                           0.83       176
   macro avg       0.54      0.54      0.54       176
weighted avg       0.81      0.83      0.82       176



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [98]:
comparison_df

Cutline_rate  Cutline_score  Predicted_rate  Predicted_score
625             2              5               2                2
301             1              0               1                2
49              1              4               1                9
616             2              8               1                3
398             1              7               1                2
..            ...            ...             ...              ...
357             1              3               1                1
195             2              8               1                8
437             2              5               2                9
587             2              8               1                3
748             1              5               1                8

[176 rows x 4 columns]

In [84]:
y_pred

array([236.2, 274.6, 277.3, 231.7, 288.3, 283.5, 247.8, 288.2, 270.9,
       263.6, 285. , 286.6, 288.8, 279.1, 275.8, 236.2, 235.7, 268.5,
       268.7, 241.2, 199.4, 182.7, 251.3, 222.6, 259.5, 279.4, 280.4,
       209.3, 287.2, 219.7, 221.8, 265.7, 280.4, 234.5, 238. , 239.8,
       287.9, 283.6, 287.4, 275.3, 286.5, 284.1, 282.5, 269.3, 221.7,
       228.4, 279.8, 279.5, 287.9, 254.5, 270.9, 246.4, 253.2, 283.7,
       255.5, 285.8, 286. , 241.3, 233.6, 220.9, 284.1, 274.6, 287.8,
       283.8, 242.8, 285.9, 273.7, 278. , 244.9, 284.9, 250.4, 226.8,
       286.1, 206.8, 286.3, 287.2, 259.9, 279. , 287. , 260.6, 242.1,
       247.2, 247.3, 288. , 227.3, 197.5, 203.8, 280. , 281.4, 224.3,
       241.3, 276.6, 241.1, 260.6, 268. , 221. , 249.5, 281.5, 276.5,
       252.9, 279.9, 283.5, 278.4, 240.6, 229.8, 290.1, 254.7, 282.4,
       240.6, 287.7, 281.2, 282.7, 224.2, 285.2, 278. , 280.5, 275.5,
       281.6, 221.7, 275.7, 255.1, 287.3, 287.9, 290. , 266.7, 212.4,
       287.7, 286.2,

In [85]:
y_pred_custom

array([200.2, 300.6, 300.3, 200.7, 300.3, 300.5, 200.8, 300.2, 300.9,
       300.6, 300. , 300.6, 300.8, 300.1, 300.8, 200.2, 200.7, 300.5,
       300.7, 200.2, 200.4, 200.7, 300.3, 200.6, 300.5, 300.4, 300.4,
       200.3, 300.2, 200.7, 200.8, 300.7, 300.4, 200.5, 200. , 200.8,
       300.9, 300.6, 300.4, 300.3, 300.5, 300.1, 300.5, 300.3, 200.7,
       200.4, 300.8, 300.5, 300.9, 300.5, 300.9, 200.4, 300.2, 300.7,
       300.5, 300.8, 300. , 200.3, 200.6, 200.9, 300.1, 300.6, 300.8,
       300.8, 200.8, 300.9, 300.7, 300. , 200.9, 300.9, 200.4, 200.8,
       300.1, 200.8, 300.3, 300.2, 300.9, 300. , 300. , 300.6, 200.1,
       200.2, 200.3, 300. , 200.3, 200.5, 200.8, 300. , 300.4, 200.3,
       200.3, 300.6, 200.1, 300.6, 300. , 200. , 200.5, 300.5, 300.5,
       300.9, 300.9, 300.5, 300.4, 200.6, 200.8, 300.1, 300.7, 300.4,
       200.6, 300.7, 300.2, 300.7, 200.2, 300.2, 300. , 300.5, 300.5,
       300.6, 200.7, 300.7, 300.1, 300.3, 300.9, 300. , 300.7, 200.4,
       300.7, 300.2,

In [86]:
y_val.values

array([300.7, 100.4, 300.6, 200.3, 200.8, 300.8, 200.5, 300.8, 300.5,
       200.7, 300.7, 300.8, 300.7, 300.5, 200.7, 200.6, 200.8, 300.7,
       300.6, 300.5, 200.6, 300.5, 301. , 200.5, 300.4, 300.9, 200.8,
       200.4, 300.8, 200.8, 200.4, 200.7, 301. , 200.7, 200.9, 300.3,
       300.6, 300.7, 300.5, 300.5, 300.8, 300.7, 300.3, 300.3, 200.7,
       200.2, 301. , 300.5, 300.8, 300.3, 300.5, 300.2, 300.5, 300.2,
       300.4, 301. , 301. , 200.7, 200.8, 200.5, 300.8, 300.1, 300.7,
       300.8, 200.8, 300.7, 200.7, 300.3, 300.2, 300.3, 300.7, 200.7,
       300.7, 200.8, 200.8, 300.8, 200.5, 200.4, 300.3, 300.2, 300.6,
       200.8, 200.5, 200.5, 100.2, 200.2, 200.4, 300.8, 300.7, 200.6,
       300.5, 300.4, 301.1, 200.7, 200. , 100.5, 300. , 300.7, 200.8,
       200.5, 300.4, 300. , 300.7, 100.3, 200.8, 300.7, 200.7, 300.7,
       100.6, 300.8, 300.9, 300.7, 200.6, 200.6, 300.2, 300.6, 300.3,
       300.5, 200.3, 200.2, 300.4, 301. , 300.8, 301. , 200.6, 200.4,
       300.8, 300.3,

## lgbm grid search

In [ ]:

model_lgb = LGBMRegressor(
    # 기본 파라미터
    random_state=42,
    n_estimators=100,  # 대략 크게 주고, early stopping으로 조절
    boosting_type='gbdt'
)

param_grid = {
    # 트리 구조 관련
    'num_leaves': [31, 63, 127],
    'max_depth': [-1, 5, 10],
    # 규제 항
    'reg_alpha': [0, 0.1, 1],
    'reg_lambda': [0, 0.1, 1],
    # 샘플링 관련
    'feature_fraction': [1.0, 0.8, 0.6],
    'bagging_fraction': [1.0, 0.8],
    # 학습률
    'learning_rate': [0.1, 0.01],
}

# -----------------------
# 2. GridSearchCV 설정
# -----------------------
grid_search = GridSearchCV(
    estimator=model_lgb,
    param_grid=param_grid,
    scoring='neg_mean_squared_error',  # 회귀에서는 MSE, RMSE 등 사용 가능
    cv=3,  # 3-Fold 교차 검증
    verbose=1,
    n_jobs=-1  # 멀티코어 사용
)

# -----------------------
# 3. fit() 시 early_stopping_rounds 적용
# -----------------------
grid_search.fit(x_train, y_train,)


/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The LGBMRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


Fitting 3 folds for each of 972 candidates, totalling 2916 fits
[LightGBM] [Warning] feature_fraction is set=0.6, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] feature_fraction is set=0.6, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000249 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 676
[LightGBM] [Info] Number of data points in the train set: 700, number of used features: 17
[LightGBM] [Info] Start training from score 261.428857
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits

/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/_tags.py:354: FutureWarning: The LGBMRegressor or classes from which it inherits use `_get_tags` and `_more_tags`. Please define the `__sklearn_tags__` method, or inherit from `sklearn.base.BaseEstimator` and/or other appropriate mixins such as `sklearn.base.TransformerMixin`, `sklearn.base.ClassifierMixin`, `sklearn.base.RegressorMixin`, and `sklearn.base.OutlierMixin`. From scikit-learn 1.7, not defining `__sklearn_tags__` will raise an error.
  warnings.warn(


GridSearchCV(cv=3, estimator=LGBMRegressor(random_state=42), n_jobs=-1,
             param_grid={'bagging_fraction': [1.0, 0.8],
                         'feature_fraction': [1.0, 0.8, 0.6],
                         'learning_rate': [0.1, 0.01], 'max_depth': [-1, 5, 10],
                         'num_leaves': [31, 63, 127], 'reg_alpha': [0, 0.1, 1],
                         'reg_lambda': [0, 0.1, 1]},
             scoring='neg_mean_squared_error', verbose=1)

In [ ]:
# -----------------------
# 4. 결과 확인
# -----------------------
print("Best Params: ", grid_search.best_params_)
print("Best CV Score (MAE): ", -grid_search.best_score_)

# 최적 모델로 테스트 세트 성능 측정
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_val)
y_pred=y_pred.round(1)
y_pred_custom=custom_round_100(y_pred)

print('MAE : ',mean_absolute_error(y_val,y_pred_custom))
print('MSE : ',mean_squared_error(y_val,y_pred_custom))
print('r2 score : ',r2_score(y_val,y_pred_custom))

Best Params:  {'bagging_fraction': 1.0, 'feature_fraction': 0.6, 'learning_rate': 0.1, 'max_depth': 5, 'num_leaves': 31, 'reg_alpha': 0, 'reg_lambda': 0}
Best CV Score (MAE):  1598.4521421688085
[LightGBM] [Warning] feature_fraction is set=0.6, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
MAE :  16.689204545454544
MSE :  1758.0724431818182
r2 score :  0.3612375806926239


/usr/local/lib/python3.11/dist-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(


In [ ]:
y_pred_custom

array([200.4, 300. , 300.3, 200.5, 300.8, 300. , 200.8, 300.1, 300.7,
       200.2, 300.9, 300.9, 300.5, 300.6, 200.5, 200.5, 300.4, 300.7,
       300.7, 300.1, 300. , 200.3, 300.4, 300. , 200.4, 300.2, 300. ,
       300.5, 300.2, 200.3, 300.4, 200.9, 300.3, 200.1, 200.6, 200.7,
       300.4, 300.9, 200.5, 300. , 200.1, 300.9, 300.6, 300.9, 200.2,
       300. , 300.6, 300.5, 300.8, 300.1, 300.6, 300.5, 300.7, 300.1,
       300.3, 300. , 300.5, 300.3, 200.6, 200. , 200.7, 300.7, 200.4,
       200.8, 300.1, 300.1, 300.6, 300.5, 300.9, 200.6, 300.7, 300.4,
       300.4, 300.1, 200.7, 200.1, 300.7, 300.5, 200. , 300.8, 200.2,
       200.4, 300. , 200.9, 200.1, 200.9, 300.9, 200.8, 300.2, 300.4,
       300.2, 300.4, 300.3, 300.2, 200.5, 300. , 300.3, 300.6, 200.2,
       300.8, 300.8, 300.6, 300.3, 300. , 300.4, 300. , 300.8, 200.9,
       300.2, 200.9, 200.5, 300.7, 300.3, 300.7, 200.4, 300.9, 300.4,
       300.6, 300.9, 300.8, 300.5, 300.5, 300.6, 200.6, 200.7, 300.2,
       300.5, 300.7,

In [ ]:
y_val.values

array([200.5, 300. , 300.4, 200.8, 300.7, 300.3, 200.8, 200.2, 300.6,
       200.7, 300.6, 300.8, 300.3, 300.5, 200.9, 200.6, 300.4, 100.4,
       300.2, 300.2, 300.7, 200.7, 300.8, 300.5, 200.8, 200.5, 300.6,
       300.4, 300.7, 200.2, 300.6, 200.8, 300.8, 300. , 200.5, 200.7,
       300.9, 300.5, 200.7, 300.9, 200.5, 300.4, 300.8, 300.7, 100.2,
       300.7, 200.7, 300.5, 300.9, 200.8, 300.5, 300.8, 300.7, 300.3,
       300.5, 300.5, 300.5, 300.5, 200.8, 200.2, 200.6, 300.7, 200.7,
       200.5, 300.6, 300.5, 300.5, 300.5, 300.5, 300.3, 200.8, 300.8,
       200.7, 300.6, 300.5, 200.7, 300.7, 300.6, 300.3, 300.8, 200.8,
       200.7, 300.3, 200.7, 300.4, 200.5, 300.6, 200.7, 300.3, 300.2,
       300.7, 200.7, 300. , 200.6, 200.8, 300.5, 200.5, 300.8, 200.7,
       300.7, 300.7, 200.5, 300.9, 300.7, 300.4, 200.7, 300.8, 200.7,
       300.3, 300.4, 200. , 300.7, 300.5, 300.5, 200.5, 300.5, 300.2,
       300.6, 300.5, 300.2, 300.8, 300.2, 301. , 200.5, 200.7, 300.8,
       300.2, 300.9,

# 4.딥러닝 이용해서 통합점수 예측해보기

In [ ]:
x.shape

(876, 18)

In [ ]:
# 기본 딥러닝 구조 만들기
model=Sequential([Input(shape=(x.shape[1],)),
                  Dense(64,activation='relu'),
                  BatchNormalization(),
                  Dropout(0.2),
                  Dense(32,activation='relu'),
                  BatchNormalization(),
                  Dropout(0.2),
                  Dense(18,activation='relu'),
                  BatchNormalization(),
                  Dropout(0.2),
                  Dense(1,activation='linear')])

# 컴파일
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['mean_absolute_error'])

# es=EarlyStopping()

# 학습
history=model.fit(x_train,y_train,epochs=50,validation_split=0.2,batch_size=32,verbose=1).history



Epoch 1/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 9s 181ms/step - loss: 12.4892 - mean_absolute_error: 3.1969 - val_loss: 11.4517 - val_mean_absolute_error: 3.3303
Epoch 2/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.2495 - mean_absolute_error: 3.0813 - val_loss: 9.2640 - val_mean_absolute_error: 2.9813
Epoch 3/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.0366 - mean_absolute_error: 2.9267 - val_loss: 8.0167 - val_mean_absolute_error: 2.7617
Epoch 4/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.2822 - mean_absolute_error: 2.7931 - val_loss: 7.2007 - val_mean_absolute_error: 2.6079
Epoch 5/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8.6794 - mean_absolute_error: 2.7050 - val_loss: 6.5428 - val_mean_absolute_error: 2.4773
Epoch 6/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.8495 - mean_absolute_error: 2.5528 - val_loss: 6.1128 - val_mean_absolute_error: 2.3879
Epoch 7/50
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.6493 - mean_absolute_error: 2.5621 - val_loss:

In [ ]:
mse, mae = model.evaluate(x_val, y_val, verbose=0)
print(f"Test MSE: {mse:.4f}, Test MAE: {mae:.4f}")

# 예측값
y_pred = model.predict(x_val)
y_pred=y_pred.round(1)
print('MAE : ',mean_absolute_error(y_val,y_pred))
print('MSE : ',mean_squared_error(y_val,y_pred))
print('r2 score : ',r2_score(y_val,y_pred))

Test MSE: 0.2485, Test MAE: 0.4103
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
MAE :  0.41022727530110975
MSE :  0.24772727102041675
r2 score :  0.2228659908541294


In [ ]:
y_pred

array([[2.7],
       [3.1],
       [2.7],
       [3. ],
       [3.4],
       [3.3],
       [2.9],
       [3.4],
       [3. ],
       [2.6],
       [3.2],
       [3.5],
       [3.5],
       [3.3],
       [3.3],
       [2.7],
       [2.1],
       [1.7],
       [3. ],
       [3.2],
       [3. ],
       [2.5],
       [3.6],
       [3. ],
       [3.2],
       [3.1],
       [3. ],
       [2.8],
       [3.1],
       [1.9],
       [3. ],
       [2.8],
       [3.4],
       [3.4],
       [2.8],
       [3. ],
       [3.3],
       [2.8],
       [3.1],
       [3.6],
       [2.7],
       [3.1],
       [3.5],
       [3.7],
       [2.5],
       [3.2],
       [3.5],
       [3.1],
       [3.6],
       [3.3],
       [3.1],
       [3.3],
       [2.8],
       [3.1],
       [3.3],
       [2.4],
       [3. ],
       [3.2],
       [3.1],
       [2.3],
       [3.1],
       [3.5],
       [3.3],
       [2.4],
       [3.4],
       [3.4],
       [3. ],
       [3.5],
       [3.3],
       [2.9],
       [3.1],
      

In [ ]:
y_val.values

array([2.5, 3. , 3.4, 2.8, 3.7, 3.3, 2.8, 2.2, 3.6, 2.7, 3.6, 3.8, 3.3,
       3.5, 2.9, 2.6, 3.4, 1.4, 3.2, 3.2, 3.7, 2.7, 3.8, 3.5, 2.8, 2.5,
       3.6, 3.4, 3.7, 2.2, 3.6, 2.8, 3.8, 3. , 2.5, 2.7, 3.9, 3.5, 2.7,
       3.9, 2.5, 3.4, 3.8, 3.7, 1.2, 3.7, 2.7, 3.5, 3.9, 2.8, 3.5, 3.8,
       3.7, 3.3, 3.5, 3.5, 3.5, 3.5, 2.8, 2.2, 2.6, 3.7, 2.7, 2.5, 3.6,
       3.5, 3.5, 3.5, 3.5, 3.3, 2.8, 3.8, 2.7, 3.6, 3.5, 2.7, 3.7, 3.6,
       3.3, 3.8, 2.8, 2.7, 3.3, 2.7, 3.4, 2.5, 3.6, 2.7, 3.3, 3.2, 3.7,
       2.7, 3. , 2.6, 2.8, 3.5, 2.5, 3.8, 2.7, 3.7, 3.7, 2.5, 3.9, 3.7,
       3.4, 2.7, 3.8, 2.7, 3.3, 3.4, 2. , 3.7, 3.5, 3.5, 2.5, 3.5, 3.2,
       3.6, 3.5, 3.2, 3.8, 3.2, 4. , 2.5, 2.7, 3.8, 3.2, 3.9, 3.8, 2.6,
       2.6, 3.8, 3.8, 3.9, 3.7, 3.5, 2.7, 2.8, 4. , 3.5, 2.6, 3.5, 3.8,
       3.5, 3.2, 3.5, 3.2, 3.8, 2.6, 4. , 3.8, 3.2, 1.6, 3.9, 2.6, 3.7,
       3.4, 1.2, 3.9, 2.7, 3.6, 2.2, 3.7, 3.7, 3.5, 3.3, 4. , 3.7, 3.7,
       3.7, 3.5, 3.3, 2.8, 2.5, 2.8, 3.5])

# 5. CatBoost 사용하기

## catboost용 데이터 전처리하기

In [ ]:
data_df.head(3)

Name          Address   Latitude   Longitude Supply_type  \
0  S-HOUSE    성동구 고산자로17길 9  37.567360  127.035712         21B   
1  S-HOUSE  성동구 고산자로17길 9-1  37.567382  127.035586         21B   
2    STAY온  관악구 남부순환로157길 3  37.484155  126.918585         17B   

   Applicant_type  Units  Gender  Shared  Cutline_rate  ...  Counts_laundry  \
0               0     12       2       0             1  ...               5   
1               0     12       2       0             1  ...               5   
2               0     23       2       0             2  ...              15   

   Counts_pharmacy  Counts_cafe  Counts_convstore  Counts_station  \
0                7           15                15               7   
1                7           15                15               7   
2               15           15                15               3   

   Infra_score  people  Rate1  Rate2  Rate3  
0         4.30     458     34    154    270  
1         4.30     442     32    148    262  
2         4.85     296     19    100    177  

[3 rows x 26 columns]

In [ ]:
trial_df=data_df.copy()
trial_df.head(2)

Name          Address   Latitude   Longitude Supply_type  \
0  S-HOUSE    성동구 고산자로17길 9  37.567360  127.035712         21B   
1  S-HOUSE  성동구 고산자로17길 9-1  37.567382  127.035586         21B   

   Applicant_type  Units  Gender  Shared  Cutline_rate  ...  Counts_laundry  \
0               0     12       2       0             1  ...               5   
1               0     12       2       0             1  ...               5   

   Counts_pharmacy  Counts_cafe  Counts_convstore  Counts_station  \
0                7           15                15               7   
1                7           15                15               7   

   Infra_score  people  Rate1  Rate2  Rate3  
0          4.3     458     34    154    270  
1          4.3     442     32    148    262  

[2 rows x 26 columns]

In [ ]:
cols=['Name','Address','Counts_daiso', 'Counts_supermarket', 'Counts_laundry',
       'Counts_pharmacy','Latitude','Longitude']


trial_df=trial_df.drop(columns=cols)

In [ ]:
trial_df.columns

Index(['Supply_type', 'Applicant_type', 'Units', 'Gender', 'Shared',
       'Cutline_rate', 'Cutline_score', 'Year', 'Quarter', 'Applied_type',
       'Counts_daiso', 'Counts_supermarket', 'Counts_laundry',
       'Counts_pharmacy', 'Counts_cafe', 'Counts_convstore', 'Counts_station',
       'Infra_score', 'people', 'Rate1', 'Rate2', 'Rate3'],
      dtype='object')

## 모델링

In [ ]:
# [0] 예시: 데이터 준비
# trial_df 내의 'Cutline_rate', 'Cutline_score'를 타겟으로 분리
X = trial_df.drop(columns=['Cutline_rate', 'Cutline_score'])
y_rate = trial_df['Cutline_rate']
y_score = trial_df['Cutline_score']

# 범주형 피처(컬럼명 리스트)
cat_features = ['Supply_type']

# [1] Train-Test Split
X_train, X_test, y_rate_train, y_rate_test, y_score_train, y_score_test = train_test_split(
    X, y_rate, y_score,
    test_size=0.2,
    random_state=24
)

# [2] 분류 모델: CatBoostClassifier
classifier = CatBoostClassifier(
    iterations=1000,
    depth=8,
    learning_rate=0.1,
    loss_function='MultiClass',
    cat_features=cat_features,  # 범주형 컬럼
    verbose=0,
    one_hot_max_size=10,
    task_type='GPU'
)

# 분류 모델 학습
classifier.fit(X_train, y_rate_train)

# Train/Test 분류 예측
y_rate_pred_train = classifier.predict(X_train).astype(int)
y_rate_pred_test = classifier.predict(X_test).astype(int)

# [3] 분류 결과를 새 피처로 추가
X_train_reg = X_train.copy()
X_train_reg['pred_rate'] = y_rate_pred_train

X_test_reg = X_test.copy()
X_test_reg['pred_rate'] = y_rate_pred_test

# [4] 회귀 모델: CatBoostRegressor
regressor = CatBoostRegressor(
    iterations=1000,
    depth=8,
    learning_rate=0.1,
    loss_function='RMSE',
    cat_features=cat_features,
    verbose=0,
    task_type='GPU'
)

# 회귀 모델 학습
regressor.fit(X_train_reg, y_score_train)

# Test 데이터 예측
y_score_pred = regressor.predict(X_test_reg)

y_score_pred.round().astype(int)

# 결과 확인
print('Rate : ',classification_report(y_rate_test,y_rate_pred_test))
print('Rate CM:',confusion_matrix(y_rate_test,y_rate_pred_test))
print('Score MAE:',mean_absolute_error(y_score_test,y_score_pred))
print('Score R2:',r2_score(y_score_test,y_score_pred))

Rate :                precision    recall  f1-score   support

           1       0.85      0.93      0.89       114
           2       0.76      0.67      0.71        55
           3       0.50      0.14      0.22         7

    accuracy                           0.82       176
   macro avg       0.70      0.58      0.61       176
weighted avg       0.81      0.82      0.81       176

Rate CM: [[106   8   0]
 [ 17  37   1]
 [  2   4   1]]
Score MAE: 1.7053806647705185
Score R2: 0.06289762824740619


In [ ]:
print(classification_report(y_rate_test,y_rate_pred_test))
print(confusion_matrix(y_rate_test,y_rate_pred_test))

              precision    recall  f1-score   support

           1       0.82      0.90      0.86       103
           2       0.78      0.71      0.74        65
           3       0.67      0.25      0.36         8

    accuracy                           0.80       176
   macro avg       0.75      0.62      0.65       176
weighted avg       0.80      0.80      0.79       176

[[93 10  0]
 [18 46  1]
 [ 3  3  2]]


In [ ]:
y_score_pred.round().astype(int)

array([5, 3, 6, 6, 6, 7, 5, 8, 6, 5, 6, 7, 4, 5, 6, 5, 5, 6, 5, 6, 5, 4,
       5, 6, 5, 7, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 7, 7, 6, 6, 5,
       5, 3, 7, 5, 9, 5, 6, 5, 4, 6, 5, 9, 6, 5, 5, 4, 8, 3, 6, 7, 6, 6,
       5, 4, 5, 6, 6, 5, 6, 6, 5, 8, 5, 6, 5, 5, 3, 6, 5, 6, 3, 4, 5, 7])

In [ ]:
y_score_test.values

array([ 7,  4,  6,  3,  8,  8,  5,  8,  5,  7,  7,  8,  7,  5,  7,  6,  8,
        7,  6,  5,  6,  5, 10,  5,  4,  9,  8,  4,  8,  8,  4,  7, 10,  7,
        9,  3,  6,  7,  5,  5,  8,  7,  3,  3,  7,  2, 10,  5,  8,  3,  5,
        2,  5,  2,  4, 10, 10,  7,  8,  5,  8,  1,  7,  8,  8,  7,  7,  3,
        2,  3,  7,  7,  7,  8,  8,  8,  5,  4,  3,  2,  6,  8,  5,  5,  2,
        2,  4,  8,  7,  6,  5,  4, 11,  7,  0,  5,  0,  7,  8,  5,  4,  0,
        7,  3,  8,  7,  7,  7,  6,  8,  9,  7,  6,  6,  2,  6,  3,  5,  3,
        2,  4, 10,  8, 10,  6,  4,  8,  3,  7,  9,  5,  7,  1,  8,  5,  6,
        2,  8,  5,  3,  5,  7,  4,  5,  6,  3,  5,  7,  7, 10,  1,  7,  9,
        7,  8,  7,  5,  5,  5,  6,  2,  8,  4,  2,  8,  7,  5,  8,  5,  7,
        5,  5,  5,  5,  6,  8])

In [ ]:
print(mean_absolute_error(y_score_test,y_score_pred))
print(r2_score(y_score_test,y_score_pred))

1.6597793753709789
0.15849025582934861


In [ ]:
cat_features

['Supply_type', 'Gender', 'Applicant_type']

# 상관계수 분석

In [ ]:
import scipy.stats as spst

In [ ]:
result=spst.pearsonr(trial_df['Cutline_score'], trial_df['Cutline_rate'])

print(f'r:{result[0]}')
print(f'pv: {result[1]}')

r:-0.07820282174370122
pv: 0.02062206957006428


In [ ]:
result=spst.pearsonr(trial_df['Cutline_score'], trial_df['Infra_score'])

print(f'r:{result[0]}')
print(f'pv: {result[1]}')

r:-0.012447292698314868
pv: 0.7129519509078379


In [ ]:
trial_df.corr(numeric_only=True)

Latitude  Longitude  Applicant_type     Units    Gender  \
Latitude            1.000000   0.247904        0.072319  0.005590 -0.068608   
Longitude           0.247904   1.000000        0.068088 -0.012358 -0.034781   
Applicant_type      0.072319   0.068088        1.000000  0.017102  0.074129   
Units               0.005590  -0.012358        0.017102  1.000000  0.075098   
Gender             -0.068608  -0.034781        0.074129  0.075098  1.000000   
Shared              0.075866   0.023712       -0.047389 -0.081407 -0.920316   
Cutline_rate       -0.114074  -0.195654        0.145300  0.113714  0.030809   
Cutline_score      -0.000582   0.082855       -0.260042 -0.072870 -0.076850   
Year                0.020348   0.024218        0.216357 -0.067156  0.074572   
Quarter             0.030345   0.037211        0.127645  0.025689  0.051038   
Applied_type       -0.070243  -0.070480       -0.445848 -0.036652 -0.036222   
Counts_daiso       -0.202724   0.057100        0.046564 -0.060478  0.064513   
Counts_supermarket -0.030898   0.181348        0.019488  0.029215 -0.017364   
Counts_laundry     -0.186463   0.079931        0.161009  0.013834  0.130917   
Counts_pharmacy    -0.024078   0.199105        0.156372  0.009341  0.012733   
Counts_cafe         0.145361   0.203567        0.037488 -0.034027 -0.040692   
Counts_convstore   -0.058703   0.036499        0.077393  0.037903 -0.067939   
Counts_station      0.016355   0.126909        0.158866 -0.007181  0.102375   
Infra_score        -0.067984   0.169410        0.140263  0.011975 -0.001530   
people             -0.019245   0.078384       -0.083617  0.491726  0.078343   
Rate1              -0.016134   0.084622       -0.100636  0.507203  0.084734   
Rate2              -0.011979   0.076047       -0.074542  0.426708  0.076137   
Rate3              -0.026170   0.078068       -0.088781  0.541617  0.077909   

                      Shared  Cutline_rate  Cutline_score      Year   Quarter  \
Latitude            0.075866     -0.114074      -0.000582  0.020348  0.030345   
Longitude           0.023712     -0.195654       0.082855  0.024218  0.037211   
Applicant_type     -0.047389      0.145300      -0.260042  0.216357  0.127645   
Units              -0.081407      0.113714      -0.072870 -0.067156  0.025689   
Gender             -0.920316      0.030809      -0.076850  0.074572  0.051038   
Shared              1.000000     -0.037886       0.077938 -0.057722 -0.049206   
Cutline_rate       -0.037886      1.000000      -0.078203 -0.152652 -0.069613   
Cutline_score       0.077938     -0.078203       1.000000  0.172129 -0.121320   
Year               -0.057722     -0.152652       0.172129  1.000000 -0.282212   
Quarter            -0.049206     -0.069613      -0.121320 -0.282212  1.000000   
Applied_type        0.022625      0.098821       0.028272 -0.424007 -0.330415   
Counts_daiso       -0.075183     -0.129327      -0.001304  0.068424  0.000476   
Counts_supermarket  0.012014     -0.021864       0.018210  0.033992 -0.078120   
Counts_laundry     -0.143330     -0.052317      -0.042675  0.100974 -0.048377   
Counts_pharmacy    -0.017129     -0.079522      -0.033644  0.087530  0.015017   
Counts_cafe         0.044215     -0.142125       0.011402  0.069288 -0.031715   
Counts_convstore    0.072632     -0.131018       0.011795  0.101195 -0.061362   
Counts_station     -0.080123     -0.194268       0.015656  0.182349  0.149234   
Infra_score        -0.001449     -0.141894      -0.012447  0.121812 -0.042663   
people             -0.078287     -0.156256       0.080889  0.157682  0.141333   
Rate1              -0.084713     -0.193508       0.080329  0.144509  0.143112   
Rate2              -0.077376     -0.149092       0.075436  0.164897  0.172807   
Rate3              -0.076574     -0.155820       0.084210  0.147728  0.106337   

                    ...  Counts_laundry  Counts_pharmacy  Counts_cafe  \
Latitude            ...       -0.186463        -0.024078     0.145361   
Longitude           ...        0

In [ ]:
correlation = trial_df['people'].corr(trial_df['Infra_score'])
print("Correlation between Cutline_rate and Cutline_score:", correlation)

Correlation between Cutline_rate and Cutline_score: 0.09213404222035312
